### ISSUE TITLE
Profiles with set frequencies

### ISSUE THREAD

**Issue by bennigraf** [RussellAult/WWB-Equipment-Profiles#7]
Hi there! I really like the idea of this repository. Now I tried to create a profile for the entry level Sennheiser XSW device series, which doesn't allow one to freely set frequencies but only provides banks of preset frequencies to choose from. Do you know if it's possible to create a WWB device profile that incorporates such a list? I.e.:

![grafik](https://github.com/RussellAult/WWB-Equipment-Profiles/assets/108006/995e2939-b6ec-4a66-b99a-fb3f95cf68ed)

My current process is to have the system calculate a free frequency, find one in the table that's as close as possible, use that in WWB and press Analyze so it tells me whether it's fine to use.

Best,
Benni.

**Comment by RussellAult** [comment]
I haven't done this myself, but it's definitely possible; take a look at Diogo's recently-submitted MIPRO ACT-8 profiles for an example
